[zh-cn]
LanguageName = "中文"
weight = 1
title = "方舟"
author = "fang2hou"
description = """
硕士研究生 @ 筑波大学
全栈工程师
"""
singleDateFormat = "2006 年 1 月 2 日"
indexDateFormat = "2006 年 1 月 2 日"
listDateFormat = "1/2"

[ja]
LanguageName = "日本語"
weight = 2
title = "方 舟"
author = "fang2hou"
description = """
博士前期 @ 筑波大学
フルスタックエンジニア
"""
customCss = ["css/fang2hou.css", "css/japanese.css"]
singleDateFormat = "2006 年 1 月 2 日"
indexDateFormat = "2006 年 1 月 2 日"
listDateFormat = "1/2"

[en]
LanguageName = "English"
weight = 3
title = "Zhou Fang"
author = "fang2hou"
description = """
Master's Candidate @ University of Tsukuba
Full Stack Developer
"""
customCss = ["css/fang2hou.css", "css/english.css"]
